ChargeTimeEU/Java-OCA-OCPP

ocpp-common/src/test/java/eu/chargetime/ocpp/test/ClientTest.java, ocpp-common/src/test/java/eu/chargetime/ocpp/test/CommunicatorTest.java, ocpp-common/src/test/java/eu/chargetime/ocpp/test/ServerTest.java, ocpp-common/src/test/java/eu/chargetime/ocpp/test/SessionTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ClientCoreProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ClientRemoteTriggerProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ClientSmartChargingProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ServerCoreProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ServerRemoteTriggerProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ServerSmartChargingProfileTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/test/AuthorizeConfirmationTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/test/MeterValueTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/test/MeterValuesRequestTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/test/JSONCommunicatorTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/test/SOAPCommunicatorTest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/test/TimeoutSessionTest.java
Use MockitoJUnitRunner to create mock instances for "@Mock"-annotated test class fields.
=> Use MockitoJUnitRunner to create mock instances in tests

ocpp-common/pom.xml, ocpp-common/src/main/java/eu/chargetime/ocpp/Client.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Communicator.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Queue.java, ocpp-common/src/main/java/eu/chargetime/ocpp/RequestDispatcher.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java, ocpp-common/src/main/java/eu/chargetime/ocpp/utilities/ModelUtil.java, ocpp-common/src/test/java/eu/chargetime/ocpp/utilities/test/ModelUtilTest.java, ocpp-v1_6-test/pom.xml, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPClient.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPCommunicator.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPSyncHelper.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WSHttpHandler.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceReceiver.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/SampledValue.java
* also use logback as default logging for tests
* use jul-over-slf4j to catch jul messages
* replaced all e(x).printStacktrace with logger.(error|warn|info)
messages
* specialized ModelUtil::isAmong to Strings (because it is only used for
that), this got rid of some warnings
=> added logging based on slf4j

.gitignore, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPSyncHelper.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/package-info.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/test/SOAPCommunicatorTest.java
Small changes to get an Ocpp1.6 soap request through, main fix is done to get the namespace interpreted:
* Using getTextContent() in SOAPSyncHelper to get the "From" Address soap header as well
* Xml schema annotation (package-info) fixed to include namespace prefix "ns"
* WebServiceListener fixed to add "toUrl" in SessionInformation. This holds soap server address of the pole
* Ignored Idea editor files that aren't needed in vcs for a maven project
=> Add a namespace fix to get 1.6 soap request through

ocpp-common/pom.xml, ocpp-common/src/main/java/eu/chargetime/ocpp/Client.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Communicator.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Queue.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java, ocpp-common/src/main/java/eu/chargetime/ocpp/SimplePromiseFulfiller.java, ocpp-common/src/main/java/eu/chargetime/ocpp/model/CallErrorMessage.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPClient.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPCommunicator.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/SOAPSyncHelper.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WSHttpHandler.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceReceiver.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/SampledValue.java
See links below for reasons:
http://javarevisited.blogspot.de/2013/08/why-use-sl4j-over-log4j-for-logging-in.html
https://logback.qos.ch/reasonsToSwitch.html
=> Switched logging to slf4j + logback.

ocpp-common/src/main/java/eu/chargetime/ocpp/ListenerEvents.java, ocpp-common/src/main/java/eu/chargetime/ocpp/ServerEvents.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/IServerAPI.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONClient.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONServer.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceReceiver.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java
Minor cleanup, minor bug while setting ping interval  fixed.
=> 0.5 cleanup

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/DiagnosticsStatusNotificationConfirmation.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/FirmwareStatusNotificationConfirmation.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/UpdateFirmwareConfirmation.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/UpdateFirmwareRequest.java
I mixed up branches and put my changes on your comments to another branch with amend option. They are in this PR.
=> Small changes for PR #56.

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/UpdateFirmwareRequest.java
Since retries are optional it may never have been set, meaning the field
could be null.
In order to avoid a NullPointerException the return type Integer is
used.
=> Let #getRetries() return an Integer instead of int

ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/DummyHandlers.java, ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/FakeCentralSystem.java, ocpp-v1_6-test/src/test/groovy/eu/chargetime/ocpp/test/base/json/JSONBaseSpec.groovy, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONServer.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerFirmwareManagementEventHandler.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ServerFirmwareManagementProfile.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/feature/profile/test/ServerFirmwareManagementProfileTest.java
Add session UUID to server firmware management handler to be able to tie requests to certain session
=> Add UUID parameter to server firmware management handler

ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/FakeCentralSystem.java, ocpp-v1_6-test/src/test/groovy/eu/chargetime/ocpp/test/base/json/JSONBaseSpec.groovy, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONServer.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java
JSONServer fixed to be backward compatible with previous versions of clients
Minor cleanup issues fixed in WebSocketListener
=> Fixes for compatibility and cleanup issues

ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/DummyHandlers.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/StartTransactionConfirmation.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/test/StartTransactionConfirmationTest.java
According to the OCPP 1.6 Standard the `transactionId` is a required field in the `StartTransactionConfirmation`. Some charging stations can not handle a missing `transactionId`. Therefore I added it to the `validate()` method and added some unit tests.
=> Add transactionId to validation method of StartTransactionConfirmation

ocpp-common/src/main/java/eu/chargetime/ocpp/FeatureRepository.java, ocpp-common/src/test/java/eu/chargetime/ocpp/test/FeatureRepositoryTest.java
the backing data structure for features was an ArrayList, which has O(n) worst-case
look-up performance. since the method findFeature(...) is frequently used, this has negative
implications on the performance of the library. A HashMap is better suited for feature look-up.
=> improve FeatureRepository impl performance

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/BootNotificationConfirmation.java
Fixed boot notification confirmation validation to allow zero as a interval value.
=> Allow zero interval

ocpp-common/src/main/java/eu/chargetime/ocpp/Client.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java
Currently the `description` of the `CallErrorException` contains the `errorCode` from the CallError and not the actual description. This PR corrects this issue.
=> fix(common): set correct description from CallError

ocpp-common/src/main/java/eu/chargetime/ocpp/ZonedDateTimeAdapter.java
Addresses the following jitpack.io exception:
The following files are not formatted properly:
/home/jitpack/build/ocpp-common/src/main/java/eu/chargetime/ocpp/ZonedDateTimeAdapter.java
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':common:verifyGoogleJavaFormat'.
> Problems: formatting style violations
=> Update to fix verifyGoogleJavaFormat exception issue #106

ocpp-common/src/main/java/eu/chargetime/ocpp/AsyncPromiseFulfillerDecorator.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceReceiver.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/WebServiceTransmitter.java
Android 8's Jack has issues processing class files with lambda
operations that implicitly use classes which are not part of the
project, resulting in build failures.
Replace the four occurrences where such lambdas are used with
functionally identical but less shorthand code, so that the OCPP
library will build for Android 8.
=> Make OCPP library compatible with Android 8

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/BootNotificationConfirmation.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/ChangeAvailabilityRequest.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/MeterValuesRequest.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/firmware/GetDiagnosticsRequest.java
It seems that #105 wasn't fully fixed in #107. I also noticed that the equals method is broken since it tries to compare objects using `==` (that works only for values -128...127).
=> Really allow zero interval + fix integer comparisons

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/feature/profile/ClientCoreProfile.java
DataTransferRequests can be both initiated by the charge point as well
as the central system.
Using the ClientCoreProfile, a received DataTransferRequest cannot be
handled because the owning profile is unset.
Fix this by setting the owning profile.
=> Fix NPE on incoming DataTransferRequest

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java
This change adds support for HTTP Basic Authentication to the OCPP-J
client, via two additional JSONConfiguration parameters for username and
password. When both are set, the HTTP Basic Authentication header will
be added to the websocket connect request.
Note that HTTP Basic Authentication transmits username and password
without encryption, so for secure communication, it must be used within
a trusted channel, e.g. a secure websocket connection (WSS) or maybe an
encrypted VPN connection.
This change has originally been prepared by our former colleague:
https://github.com/rtzll/Java-OCA-OCPP/commit/8652108a08e295c063eaa7848b231d5b4c47526f
and has successfully been tested in a plugfest.
=> Add support for HTTP Basic Authentication

OCPP-J/build.gradle, OCPP-J/pom.xml, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java, ocpp-v1_6/build.gradle, ocpp-v1_6/pom.xml, ocpp-v2_0/build.gradle, ocpp-v2_0/pom.xml
The last update of the Java-WebSocket dependency to 1.5.0 changed only
the maven pom files and missed the gradle build files, which remained
at 1.3.8.
This change updates the dependency to 1.5.1 in all places, also picking
up the Java-WebSocket 1.5.1 fix for Android.
=> Bump Java-WebSocket consistently to 1.5.1

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/SampledValue.java
According to the OCPP specification, all fields of the SampledValue
class except for "value" are optional and may be omitted.
However, the Java class implementation in this library initialized all
fields but "phase" to their default values, and prevented resetting all
but the enum fields to null. Most prominently, the "unit" field was
initialized to "Wh" and could not be reset, preventing the generation of
compliant messages for "Frequency" and "Power.Factor" measurands, for
which the "unit" field needs to be omitted.
Remove the initialization of fields to their default values from the
class constructors, so that they are left as null and will be omitted
when serializing the object.
Exempt null references from the validations in the field setter methods,
so that all fields can be set to …
=> Allow omitting all optional SampledValue fields

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONCommunicator.java
ZonedDateTimeSezializer is not compatible with ISO 8601. 
Before fix ZonedDateTime was serialized as follows eg:
`2021-05-31T11:29:13.009857200+02:00[Europe/Belgrade]`
And should be:
`2021-05-31T09:29:13.009857200Z`
OCPP charger simulator https://github.com/NewMotion/docile-charge-point was not being able to parse date fields.
=> Fix ZonedDateTimeSerializer (ISO 8601)

OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java
The OCPP 1.6 Security Whitepaper foresees that the AuthorizationKey,
which is a hexadecimal string representation of the HTTP Basic
Authentication password to be used, may use the full byte range, i.e.
including non-printable characters. Thus, passing it as a Java String
object is not suitable.
In contrast, OCPP 2.0.1 specifies the password as being a string of
printable UTF-8 characters. The library already supports that.
To accomodate both, take advantage of the fact that JSONConfiguration
treats all parameters as Objects, so either a String or a byte array can
be set.
Change the code adding the credentials to the HTTP header to correctly
generate the Base64 encoded credentials from either a password string or
a byte array, depending on the object type that was set as the password.
=> Add support for non-printable HTTP passwords

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/smartcharging/ChargingRateUnitType.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/smartcharging/GetCompositeScheduleRequest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/test/GetCompositeScheduleRequestTest.java
Rename enum ChangingRateUnitType to ChargingRateUnitType and field changingRateUnitType to chargingRateUnit.
Now there are two enums ChargingRateUnitType one in core and one in smartcharging packages.
OCPP charger simulator https://github.com/NewMotion/docile-charge-point was not being able to parse GetCompositeSchedule request correctly
=> Rename enum ChangingRateUnitType to ChargingRateUnitType (Typo)

ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/localauthlist/AuthorizationData.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/localauthlist/SendLocalListRequest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/localauthlist/test/SendLocalListRequestTest.java
Fixes #151 
As per the OCPP 1.6 specs, IdTagInfo in AuthorizationData is optional when doing a SendLocalList with differential UpdateType to delete the entry.
From 7.1
`Optional. (Required when UpdateType is Full) This contains information about authorization status, expiry and parent id. For a Differential update the following applies: If this element is present, then this entry SHALL be added or updated in the Local Authorization List. If this element is absent, than the entry for this idtag in the Local Authorization List SHALL be deleted.`
=> Allow optional IdTagInfo in SendLocalList for deleting entries

ocpp-common/src/main/java/eu/chargetime/ocpp/model/Message.java
=> Add toString to Message for clearer logs

OCPP-J/pom.xml, ocpp-v2_0-test/pom.xml, ocpp-v2_0/pom.xml
Partially fixes #136 
This removes the dependency on the parent pom for OCPP-J, ocpp-v2_0 and ocpp-v2_0-test modules.
@TVolden you would need to re-deploy to Maven repo for OCPP-J and maybe deploy the 2.0 jars if needed. After deploying and it verifying it works, you can update the versions in the pom to something like 1.1-SNAPSHOT.
=> Fix Maven build/dependency error

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java
Add a new configuration parameter CONNECTION_TIMEOUT_IN_MS to specify the websocket connection timeout in milliseconds and use it when creating `WebSocketClient`. The default value is `0`, which means _no timeout_.
Fixes #158
=> Enable ws connection timeout

ocpp-common/src/main/java/eu/chargetime/ocpp/Communicator.java
TL;DR: the error flag in `Communicator `never gets set back to `false`  after it has been to to `true`
We've encountered some rare cases where...
* the charge-point has been offline
* the central-system responded with some kind of error
* now the client tries to resend non-send-messages via `RetryRunner`  but will never "pop the message"  (see code) so it will send the same message again and again
=> reset failed flag before sending retry messages

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketListener.java
`WebSocketServer `[1] offers possibility to adjust number of decoders.  It's useful to be able co configure this.
[1] https://www.javadoc.io/doc/org.java-websocket/Java-WebSocket/1.3.4/org/java_websocket/server/WebSocketServer.html#WebSocketServer-java.net.InetSocketAddress-int-
=> make number of web-socket-workers / decoders configurable

ocpp-v2_0-test/src/main/java/eu/chargetime/ocpp/test/FakeCentralSystem.java, ocpp-v2_0-test/src/main/java/eu/chargetime/ocpp/test/FakeChargePoint.java, ocpp-v2_0-test/src/main/java/eu/chargetime/ocpp/test/features/StatusNotification.java, ocpp-v2_0-test/src/test/groovy/eu.chargetime.ocpp.test/features/BootNotificationSpec.groovy, ocpp-v2_0-test/src/test/groovy/eu.chargetime.ocpp.test/features/SetVariablesSpec.groovy, ocpp-v2_0-test/src/test/groovy/eu.chargetime.ocpp.test/features/StatusNotificationSpec.groovy, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/features/basic/StatusNotificationFeature.java, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/features/basic/handlers/IServerStatusNotificationRequestHandler.java, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/model/basic/StatusNotificationConfirmation.java, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/model/basic/StatusNotificationRequest.java, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/model/basic/types/ConnectorStatusEnumType.java, ocpp-v2_0/src/main/java/eu/chargetime/ocpp/model/validation/StringMaxLengthValidationRule.java, ocpp-v2_0/src/test/java/eu/chargetime/ocpp/model/basic/test/StatusNotificationRequestTest.java
Support for status notification from OCPP 2.0
=> Support OCPP 2.0 status notification

build.gradle, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/localauthlist/SendLocalListRequest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/localauthlist/test/SendLocalListRequestTest.java
The OCPP 1.6 specification mentions no explicit value range for the
listVersion field in the SendLocalListRequest, but specifies that 0
should be returned as the version in case the list is empty. Now there
is no message to clear the local authorization list, so clearing the
list can only be achieved with a SendLocalListRequest with an empty
list, and that is a use case for listVersion 0. In fact the OCPP
certification test tool employs such requests.
Change SendLocalListRequest to allow listVersion 0 rather than only 1 or
higher, and adapt the unit test accordingly.
While at it, bump the version in build.gradle to "1.1" to match the one
from pom.xml.
=> Allow listVersion 0 in SendLocalListRequest

ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java
Fixes ChargeTimeEU/Java-OCA-OCPP#208. We already have session ID in `session` object, and can use it to make sure session is still in the `Map` keys. There is no need to check if the `session` object itself is in the `Map` values.
=> Use key when checking if session is in the Map.

ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java
Improve logging for no active session error since it's hard to check with multiple chargers.
=> Add session id to logs for no active session

OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketTransmitter.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONClient.java
The WebSocket library allows changing the ping interval immediately during an ongoing connection. Expose this capability by adding a new reconfigure() method to the JSONClient class.
To make use of this, set the updated PING_INTERVAL_PARAMETER on the JSONConfiguration object passed to the JSONClient constructor, then invoke JSONClient#reconfigure().
This has been successfully verified to work.
=> Allow JSONClient reconfiguration when connected

.github/workflows/maven.yml, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/model/core/BootNotificationRequest.java, ocpp-v1_6/src/test/java/eu/chargetime/ocpp/model/core/test/BootNotificationRequestTest.java
=> ocpp-v1_6: BootNotificationRequest: Allow optional properties to be set null

.github/workflows/maven.yml
This reverts the build script workaround introduced by #223.
#223 fixed #221.
java-version: '11' no longer delivers an incompatible JDK. See https://github.com/ChargeTimeEU/Java-OCA-OCPP/pull/223#issuecomment-1328119343 and following.
This reverts commit 3bc476e81163b8704042e27a88e8066d543137b2.
=> Revert "GitHub Actions: Downgrade maven workflow to 11.0.16+8"

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-v1_6/src/main/java/eu/chargetime/ocpp/JSONServer.java, ocpp-v2/src/main/java/eu/chargetime/ocpp/MultiProtocolJSONServer.java, ocpp-v2/src/main/java/eu/chargetime/ocpp/MultiProtocolWebSocketListener.java
This change allows the configuration of the password length with entries in JSONConfiguration.
The password length should be 20 for OCPP 1.6 and 40 for OCPP 2.0. The length of the password should be configurable for cases with longer passwords.
=> Allow configuration of allowed password string length

OCPP-J/build.gradle, OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-common/src/main/java/eu/chargetime/ocpp/ListenerEvents.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java, ocpp-common/src/main/java/eu/chargetime/ocpp/ServerEvents.java, ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/DummyHandlers.java, ocpp-v2/src/main/java/eu/chargetime/ocpp/MultiProtocolWebSocketListener.java, ocpp-v2_0-test/src/main/java/eu/chargetime/ocpp/test/FakeCentralSystem.java
- As per the 1.6 spec the authorization key should be 20 bytes long, in hex format that is 40 chars
- gson library updated due to a reported vulnerability
- Keep a single instance of JSONConfiguration.java so users can actually configure it
=> Fix for the default password max length (as per the 1.6 spec) and other minor changes

OCPP-J/src/main/java/eu/chargetime/ocpp/JSONConfiguration.java, OCPP-J/src/main/java/eu/chargetime/ocpp/WebSocketListener.java, ocpp-common/src/main/java/eu/chargetime/ocpp/ListenerEvents.java, ocpp-common/src/main/java/eu/chargetime/ocpp/Server.java, ocpp-common/src/main/java/eu/chargetime/ocpp/ServerEvents.java, ocpp-v1_6-test/src/main/java/eu/chargetime/ocpp/test/DummyHandlers.java, ocpp-v2/src/main/java/eu/chargetime/ocpp/MultiProtocolWebSocketListener.java, ocpp-v2_0-test/src/main/java/eu/chargetime/ocpp/test/FakeCentralSystem.java
These commits were based on a misunderstanding of the OCPP-J 1.6 specification, which clearly states that the password is a byte sequence and not a string. Also, they broke the ServerEvents#authenticateSession() API:
Revert "More password fixes."
This reverts commit fb5d0fb4c9e5cf8e1f14ab97ea5e15422fb441f4.
Revert "Fix password decoding."
This reverts commit cf20205e849a258ee5f4893a1d916ef8091f12d1.
Revert "Recommended by 1.6 spec is a 20 byte (40 chars) key."
This reverts commit f7b92a3d6ae51cce4e6bbdcc25148cb951e986d1.
This commit breaks the API, because the behaviour of the method is changed to return the last configuration instead of the default configuration:
Revert "A single instace, otherwise a static get() method makes no sense."
This reverts commit …
=> Revert commits breaking API and binary OCPP 1.6 passwords
